version: '3.6'
services:
  db:
    image: postgres:10.4-alpine
    env_file:
      - .pgsql.env
    volumes:
      - db:/var/lib/postgresql
    ports:
      - '5432:5432'
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/opt/app
    ports:
      - '8080:8080'